### ISSUE TITLE
Sixel image output problems, keyboard/mouse issues

### ISSUE THREAD

**Issue by klamonte** [kmgrant/macterm#4]
Hello, I am testing my [terminal user interface library Jexer](https://jexer.sourceforge.io) against MacTerm stable (4.1.20180825) and ran across the following issues:

* Sixel sequences are failing and emitting raw DCS sequences to screen.  I can 'cat' one sixel image and see it, but putting many small sixel images on the screen at once leads to garbage.

* Performance is very poor.

In addition to the sixel issues:

* Alt-keystrokes are not working.

* Mouse is not working.  Jexer requests Button-event tracking (1002) + Any-event tracking (1003) + UTF-8 encoding (1005) + SGR encoding (1006).  Mouse also does not work on plain Midnight Commander 'mc'.

* Function keys are not working.  For example, cannot exit 'mc' by pressing F10.

How I tested:

* I installed the latest stable build 4.1.20180825.

* I set MacTerm up as with Base emulator=Xterm and Identity=xterm, and made no other changes.

* I open a session, ssh to a Linux system, and 'cat' one of the captures here: https://jexer.sourceforge.io/sixel.html .

* I also try to run Jexer: 'java -jar jexer-test.jar' .  I can tab to the "Terminal" button, press enter, and then in the terminal window 'cat cjk.txt' and see DCS sequences on screen.  Unfortunately I have to kill the Java process from another terminal, or close the MacTerm shell, to exit the Jexer application, since keystrokes and mouse do not work.

**Comment by kmgrant** [comment]
Thank you for the detailed reports.
Please close and reopen unrelated problems as **separate** issues though (otherwise I cannot easily comment on or “close” them individually).
Also, please note that due to the tremendous amount of code that had to be ripped out and reimplemented when transitioning to macOS Catalina, all issues in 4.1 are “won’t fix”.  I will definitely keep track of these problems for MacTerm 5.0 though (not yet stable release), and in particular Sixel performance is definitely better with that version so far.

**Comment by kmgrant** [comment]
I can reproduce terrible Sixel performance for the case of `lady-of-shalott.six` in your test suite.  It is caused by the macOS system log writing a message on *every single pixel*!  Do you see the specific messages `Unknown number of components for colorspace model -1` and `Unrecognized colorspace number -1` in your Console log (hundreds of times) when attempting to write a Sixel image?

So far I have not been able to suppress this OS logging, nor can I detect the error as it happens (it is not triggered by an exception).  Since the messages are related to color spaces, I have tried changing some aspects of how colors are handled, which has not worked so far but it seems like the best strategy right now.

I will update this as I find out more.

**Comment by kmgrant** [comment]
The core issue of SIXEL performance has been fixed so I will close this issue.  Other features noted here, such as XTerm mouse support, are not bugs since MacTerm never claimed to support them.  If you wish, please submit the other items as _separate_ issues so that they may be implemented and closed individually (it is hard to address a variety of topics in a single GitHub Issue).

**Comment by klamonte** [comment]
@kmgrant 

FYI A sixel vulnerability was discovered by @dankamongmen and reported here: https://nvd.nist.gov/vuln/detail/CVE-2022-24130

A large repeat count within a sixel sequence can cause a crash, either from buffer under/overflow or out of memory. I cannot test MacTerm easily anymore, so just wanted to mention it to you.

https://www.openwall.com/lists/oss-security/2022/01/30/3 has a nice test script:

```
#!/bin/bash
printf "\ePq"
printf "#%hhu;2;%hhu;%hhu;%hhu" 0x41 100 100 100
printf "#%hhu!%u@" 0x41 0x7fffffff
printf "#%hhu!%u@" 0x41 0x7fffffff
printf "\e\\"
```

Some additional discussion with other terminals is here: https://gitlab.com/klamonte/jexer/-/issues/105

**Comment by kmgrant** [comment]
Thanks; I have tried this case and although it does not crash or corrupt memory, the behavior is incorrect and random (MacTerm’s repeat counter is wrapped around to a smaller value instead of, say, remaining at a maximum supported value in a consistent way).  I will come up with a fix just to stabilize the behavior.

Also, in the future, _please_ put every unique request into a separate Issue.  It is too difficult to keep track of multiple unrelated things in different threads, especially if they cannot all be closed at the same time.  Thank you!
