### ISSUE TITLE
Build on osx Catalina with Xcode 12

### ISSUE THREAD

**Issue by Nanoc-ice** [kmgrant/macterm#6]
First off, should this currently build with the code in github as of (5/17/22)?

Assuming so, I clone it locally and tried to build on Catalina with Xcode 12 and got this error:

Showing All Messages
accessing build database "/Users/XXXXXXXX/dev/terminal-emulators/macterm/Build/_Generated/XCBuildData/build.db": database is locked Possibly there are two concurrent builds running in the same filesystem location.

There is no other build running and the permissions to read and write to the filesystem has been opened for xcode.  Is this something on my end or with the code in git or something else?

**Comment by kmgrant** [comment]
Hi,

Yes, the latest code builds with Xcode 12.4 on Catalina also.

I usually build from the command line (starting from the `Build` directory and running `make`) but you can start from Xcode; if you do, make sure to choose the `Everything` target.  When this finishes the output will still be in `Build/MacTerm.app`.

I have not seen this type of database-locking error before.  I would recommend double-checking anything that could possibly be looking at this directory, such as the Finder or maybe a Terminal window, in case that is somehow preventing Xcode from modifying the same space.

Also note, in order to build MacTerm successfully you will need to resolve a couple of dependencies: Python 3 and SWIG.  By default it assumes these are resolved by Homebrew (`brew`); the file `Build/Shared/All.xcconfig` can be used to override paths if this is different.  I can give more detail on that if you like.

**Comment by Nanoc-ice** [comment]
Thanks for the quick reply. I have those dependancies except for SWIG. I get it it from home brew.  I’ll try to build from command line, but I’m thinking I will run into the same error.  Regardless I will keep looking for a resolution.

**Comment by Nanoc-ice** [comment]
Yes, I opened Xcode on one of my other projects and then re-selected the mactterm xcode project file and it opened up.  I added the account in xcode and the keychain and now it says there are duplicates found.  uggh.  It looks to be on my side and I am anxious to take a look at this, so I will keep pushing on it.

**Comment by Nanoc-ice** [comment]
Success!  I was able to build it.  Now, to try it out.
