### ISSUE TITLE
error: No certificate matching 'Developer ID' found

### ISSUE THREAD

**Issue by DesantBucie** [kmgrant/macterm#9]
Hey, i cannot build this on macOS ventura, M1.

I tried switching Sign Certificate to Run locally in XCode, but it wouldn't help.

The last few lines are:
```
Computing target dependency graph and provisioning inputs

Create build description
Build description signature: fef3408f602426793d34d58795d397ab
Build description path: /Users/dsnt/Developer/macterm/Build/_Generated/XCBuildData/fef3408f602426793d34d58795d397ab-desc.xcbuild

warning: Building targets in manual order is deprecated - check "Parallelize build for command-line builds" in the project editor, or set DISABLE_MANUAL_TARGET_ORDER_BUILD_WARNING in any of the targets in the current build to suppress this warning
/Users/dsnt/Developer/macterm/Build/Application.xcodeproj: error: No certificate matching 'Developer ID' found: Select a different signing certificate for CODE_SIGN_IDENTITY, a team that matches your selected certificate, or switch to automatic provisioning. (in target 'PythonWrapper' from project 'Application')
```

Full log 
[error.log](https://github.com/kmgrant/macterm/files/10196188/error.log)

**Comment by kmgrant** [comment]
Hi, sorry for the delayed response.

One way to resolve this problem is to export a Developer ID certificate type (which requires an Apple account).  This can be done in Xcode for example via the settings/preferences panel, Accounts, “Manage Certificates…”, and using the “+” button in the lower-left of the panel that opens to generate a Developer ID certificate.  Then the build should find it in the keychain automatically.

Another way is to change the type of signing to something that you _do_ have.  The default code-signing identity is mostly set from `Build/Shared/Signature.xcconfig` and can be overridden there, or by modifying each of the targets in the project.  For example, to fix the specific target with the error above, open `Application.xcproj`, select the project, select the `PythonWrapper` target, go to the `Build Settings` section, filter by `identity`, and then update the “Code Signing Identity” setting to something else.

**Comment by DesantBucie** [comment]
Thanks, but I have another problem. It seems I already had Developer ID cert. Now i copied the value of Developer team and code signing identity(10 words key and email with 10 words key) to the `Signature.xcconfig`. But what with DEVELOPER_ID_APP? Do i need to have paid Apple developer identification, or I just need to enter my mail there too?

Sorry if I mixed something, but I haven't used XCode much, and didn't sign things as well.

**Comment by kmgrant** [comment]
You might not need to change the team identity (the default `DEVELOPMENT_TEAM` value, which is empty, should work).

You should not need to change `DEVELOPER_ID_APP` as long as your Keychain contains an item with a common name that matches the default setting of `Developer ID Application:`.  For example, my Keychain contains a certificate-type item `Developer ID Application: Kevin Grant (…)` so that is used.

I recommend looking at the `Keychain Access` app, for `certificate` items, and see what they are called.  If they have a slightly different name, you may need to use that name instead, here.

Note also that my `DEVELOPER_ID_APP` setting is ultimately used for a `codesign --sign …` command; by running `man codesign` you can find a `SIGNING IDENTITIES` section where Apple explains all the other possible values for this.

**Comment by DesantBucie** [comment]
> You should not need to change `DEVELOPER_ID_APP` as long as your Keychain contains an item with a common name that matches the default setting of `Developer ID Application:`

I think that's the problem. I don't have it. I have **Apple Development:** (i didn't enroll to apple development program) and **Developer ID Certification Authority**.
